# Generated by Django 4.0.4 on 2022-11-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_vendor_payment_expense_banking_customer_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts2',
            fields=[
                ('accounts2id', models.AutoField(primary_key=True, serialize=False, verbose_name='ACCOUNTSID')),
                ('acctype', models.CharField(max_length=100, null=True)),
                ('detype', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('gst', models.CharField(default='', max_length=100, null=True)),
                ('deftaxcode', models.CharField(max_length=100, null=True)),
                ('balance', models.FloatField(default=0.0, null=True)),
                ('dbbalance', models.FloatField(default=0.0, null=True)),
                ('asof', models.DateField(null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
