# Generated by Django 4.0.4 on 2022-11-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_accounts2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts2',
        ),
    ]
